FROM icferst/baseimages:bionic

USER root

RUN apt-get -y update && \
      apt-get -y dist-upgrade && \
      rm -rf /var/cache/apt/archives && \
      rm -rf /var/lib/apt/lists

COPY . /home/icferst
RUN chown -R icferst /home/icferst

USER icferst

RUN ./configure --enable-2d-adaptivity
RUN make mp
RUN make fltools
