FROM fluidity/baseimages:bionic

USER root

RUN apt-get -y update && \
      apt-get -y dist-upgrade && \
      apt install -y python3-pip python3.8-venv libparmetis-dev gir1.2-gtksource-3.0  \
      && rm -rf /var/cache/apt/archives && \
      rm -rf /var/lib/apt/lists

COPY . /home/fluidity
RUN chown -R fluidity /home/fluidity

USER fluidity

RUN ./configure --enable-2d-adaptivity
RUN make mp
RUN make fltools
