input:
	gmsh -3 -format msh2 -o metal_two_region_box.msh metal_two_region_box.geo

clean:
	rm -f *.vtu *.pvtu *.stat log *.log *.halo *.err matrixdump* \
	      *checkpoint* first_timestep_adapted_mesh* *.detectors *.csv
