#!/usr/bin/env python3
import sys
import vtk
from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk
import numpy as np

if len(sys.argv) != 4:
    print("Usage: vtudiff file1.vtu file2.vtu diff.vtu")
    sys.exit(1)

file1_name, file2_name, diff_name = sys.argv[1:]

# Read first file
reader1 = vtk.vtkXMLUnstructuredGridReader()
reader1.SetFileName(file1_name)
reader1.Update()
data1 = reader1.GetOutput()

# Read second file
reader2 = vtk.vtkXMLUnstructuredGridReader()
reader2.SetFileName(file2_name)
reader2.Update()
data2 = reader2.GetOutput()

# Create diff data object
diff = vtk.vtkUnstructuredGrid()
diff.DeepCopy(data1)

# Compute differences for each point data array
for i in range(data1.GetPointData().GetNumberOfArrays()):
    arr1 = data1.GetPointData().GetArray(i)
    arr2 = data2.GetPointData().GetArray(i)
    if arr1 and arr2:
        np1 = vtk_to_numpy(arr1)
        np2 = vtk_to_numpy(arr2)
        diff_arr = np.abs(np1 - np2)
        vtk_diff_arr = numpy_to_vtk(diff_arr)
        vtk_diff_arr.SetName(arr1.GetName())
        # Zero out tiny values (< 1e-100)
        tmp = vtk_to_numpy(vtk_diff_arr)
        tmp[tmp < 1e-100] = 0
        vtk_diff_arr = numpy_to_vtk(tmp)
        vtk_diff_arr.SetName(arr1.GetName())
        diff.GetPointData().RemoveArray(arr1.GetName())
        diff.GetPointData().AddArray(vtk_diff_arr)

# Write the diff file in ASCII mode so Python can read it
writer = vtk.vtkXMLUnstructuredGridWriter()
writer.SetFileName(diff_name)
writer.SetDataModeToAscii()  # <-- change here
writer.SetInputData(diff)
writer.Write()