input:
	gmsh -3 -format msh2 -o three_layer_box_well.msh three_layer_box_well.geo

clean:
	rm -f *.vtu *.pvtu *.stat log *.log *.halo *.err matrixdump* \
	      *checkpoint* first_timestep_adapted_mesh* *.detectors *.csv
